---
version: '3'
networks:
  kafka-net:
    driver: overlay
volumes:
  manager_data: {}
  zookeeper_data: {}
  broker_1_data: {}
  broker_2_data: {}
  broker_3_data: {}
services:
  manager:
    image: zen12/kafka-manager-docker
    ports:
    - 2190:9000
    networks:
    - kafka-net
    links:
    - zookeeper
    environment:
      KM_VERSION: 1.3.3.17
      ZK_HOSTS: zookeeper:2181
    volumes:
    - manager_data:/kafka-manager
  zookeeper:
    image: zen12/kafka-cluster
    command: zookeeper
    ports:
    - 2181:2181
    networks:
    - kafka-net
  broker_1:
    hostname: broker_1
    image: zen12/kafka-cluster
    environment:
      KAFKA_BROKER_ID: 1
      HOSTNAME_COMMAND: 'docker info | grep ^Name: | cut -d'' '' -f 2'
      KAFKA_LOG_DIRS: "/kafka-data"
      KAFKA_CREATE_TOPICS: __test1:1:1,app-logs:1:3:compact
      KAFKA_LOG_RETENTION_HOURS: '168'
      KAFKA_LOG_RETENTION_BYTES: '1073741824'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - broker_1_data:/kafka-data
    ports:
    - 2091:9094
    networks:
    - kafka-net
    links:
    - zookeeper:zookeeper
  broker_2:
    hostname: broker_2
    image: zen12/kafka-cluster
    environment:
      KAFKA_BROKER_ID: 2
      HOSTNAME_COMMAND: 'docker info | grep ^Name: | cut -d'' '' -f 2'
      KAFKA_LOG_DIRS: "/kafka-data"
      KAFKA_CREATE_TOPICS: __test1:1:1,app-logs:1:3:compact
      KAFKA_LOG_RETENTION_HOURS: '168'
      KAFKA_LOG_RETENTION_BYTES: '1073741824'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - broker_2_data:/kafka-data
    ports:
    - 2092:9094
    networks:
    - kafka-net
    links:
    - zookeeper:zookeeper
  broker_3:
    hostname: broker_3
    image: zen12/kafka-cluster
    environment:
      KAFKA_BROKER_ID: 3
      HOSTNAME_COMMAND: 'docker info | grep ^Name: | cut -d'' '' -f 2'
      KAFKA_LOG_DIRS: "/kafka-data"
      KAFKA_CREATE_TOPICS: __test1:1:1,app-logs:1:3:compact
      KAFKA_LOG_RETENTION_HOURS: '168'
      KAFKA_LOG_RETENTION_BYTES: '1073741824'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - broker_3_data:/kafka-data
    ports:
    - 2093:9094
    networks:
    - kafka-net
    links:
    - zookeeper:zookeeper
